services:
  - type: web
    name: e-meli
    runtime: node
    plan: free
    buildCommand: cd server && npm install && cd ../client && npm install && npm run build
    startCommand: cd server && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: e-meli-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true

databases:
  - name: e-meli-db
    plan: free
    databaseName: emeli
    user: emeli
